### ISSUE TITLE
Edit Summary页面Markdown预览

### ISSUE THREAD

**Issue by africamonkey** [africamonkey/ICPC-Training-Summary#40]
Markdown 预览如果插入代码，它不会换行。

**Comment by Dexan-Ou** [comment]
give a sample

**Comment by africamonkey** [comment]
@Dexan-Ou 

I enter this code into the editor and save. 

\```C++
 int main() {
     return 0;
 }
\```

After markdownify, it is converted to HTML code:

```html
<code>C++
int main() {
return 0;
}
</code>
```

It seems that the line breaks are missing, and it finally looks like this:

`C++ int main() { return 0; }`

**Comment by Dexan-Ou** [comment]
fix
